#!/usr/bin/env python

import requests

data = """
{
    "class": "uk.gov.gchq.gaffer.operation.impl.add.AddElements",
    "validate": true,
    "skipInvalidElements": false,
    "input": [
	{
	    "class": "uk.gov.gchq.gaffer.data.element.Edge",
	    "properties": {
		"count": 1
	    },
	    "group": "ipflow",
	    "source": "192.168.0.1",
	    "destination": "192.168.0.2",
	    "directed": true
	},
	{
	    "class": "uk.gov.gchq.gaffer.data.element.Edge",
	    "properties": {
		"count": 1
	    },
	    "group": "ipflow",
	    "source": "192.168.0.1",
	    "destination": "192.168.0.3",
	    "directed": true
	},
	{
	    "class": "uk.gov.gchq.gaffer.data.element.Entity",
	    "properties": {
		"count": 1
	    },
	    "group": "ip",
	    "vertex": "192.168.0.1"
	},
        {
	    "class": "uk.gov.gchq.gaffer.data.element.Entity",
	    "properties": {
		"count": 1
	    },
	    "group": "ip",
	    "vertex": "192.168.0.2"
	},
        {
	    "class": "uk.gov.gchq.gaffer.data.element.Entity",
	    "properties": {
		"count": 1
	    },
	    "group": "ip",
	    "vertex": "192.168.0.3"
	}
    ]
}
"""

url = "http://localhost:8080/rest/v2/graph/operations/execute"

response = requests.post(url, data, headers={'content-type':'application/json'})

print "Status:",response.status_code
print response.text

