#!/usr/bin/env python

import requests

gafferAddElements = """{
"class": "uk.gov.gchq.gaffer.operation.impl.add.AddElements",
"validate": true,
"skipInvalidElements": false,
"input":"""

gafferEndAddElements = """
}
"""

data = """
{
   "class": "uk.gov.gchq.gaffer.operation.impl.get.GetAllElements"
}
"""

url = 'http://localhost:8080/rest/v2/graph/operations/execute'

print "Starting request"

response = requests.post(url, data,
                         headers={'content-type': 'application/json'},stream=True)

print "Status:",response.status_code
print "Starting xfer"

with open("all.json", 'wb') as f:
	f.write(gafferAddElements)
	for chunk in response.iter_content(chunk_size=1024):
		f.write(chunk)
	f.write(gafferEndAddElements)
print "Done xfer"
